###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mailhog:
      image: mailhog/mailhog:latest
      container_name: sjdemo-mailhog
      ports:
        - "8001:8025"

    mariadb:
      image: mariadb:10.4
      container_name: sjdemo-mariadb
      working_dir: /application
      volumes:
        - ./code:/application
      environment:
        - MYSQL_ROOT_PASSWORD=%%
        - MYSQL_DATABASE=%%
        - MYSQL_USER=%%
        - MYSQL_PASSWORD=%%
      ports:
        - "8003:3306"

    webserver:
      image: nginx:alpine
      container_name: sjdemo-webserver
      working_dir: /application
      volumes:
          - ./code:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
       - "443:443"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: sjdemo-php-fpm
      working_dir: /application
      volumes:
        - ./code:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

